### PR TITLE
Faq

### PR DESCRIPTION
**Pull request by melvo**

### CODE REVIEW

**Review by cal0pteryx — CHANGES_REQUESTED** [review]
The spacing at the end of faq.md is necessary for browsers to be able to jump to heading anchors correctly. If there is not enough space at the end of the page, the browser jumps to the bottom, but does not necessarily but the desired heading at the top (as one would expect).

**Comment by melvo** [comment]
@cal0pteryx But that depends on the web browser's height. When I open https://providers.xmpp.net/faq/#server-to-server that is not at the top of the page. Thus, we would need to know the height instead of using a random number of `spacer` elements.

**Comment by cal0pteryx** [comment]
There is absolutely no need to make this complicated.

**Comment by cal0pteryx** [comment]
We now have anchor highlighting, which makes the extra spacing obsolete.

**Review by cal0pteryx — APPROVED** [review]

**Pull request merged**
